// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSCT compiler.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AICA
{
    using System;
    
    internal sealed partial class PackageIds
    {
        public const int AICA_MenuGroup = 0x1000;
        public const int AICA_CommandGroup = 0x1001;
        public const int AICA_Menu = 0x1002;
        public const int OpenChatCommand = 0x0100;
        public const int ExplainCodeCommand = 0x0101;
        public const int RefactorCommand = 0x0102;
        public const int GenerateTestCommand = 0x0103;
        public const int OpenChatWindowMenuCommand = 0x0104;
    }
}
